//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.AccesoDatos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SACC.AccesoDatos.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[spServicio_Consultar] 
        ///	@Opcion              SMALLINT	  = 0,
        ///	@ServicioId          INT          = 0,
        ///	@ServicioDescripcion VARCHAR(100) = &apos;&apos;,
        ///	@ServicioTipoId      INT		  = 0,
        ///	@Baja                BIT		  = NULL
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///
        ///	/* OPCION PARA CONSULTAR EL REGISTRO */
        ///	IF @Opcion = 1
        ///	BEGIN
        ///		SELECT 	a.ServicioId,
        ///				a.ServicioDescripcion,
        ///				a.ServicioTipoId,
        ///				a.Codigo,
        ///				a.CodigoAlterno,
        ///				a.Especial,
        ///				a.MostrarHospitalizacion,
        ///				a.Adqu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertaPaquete {
            get {
                return ResourceManager.GetString("InsertaPaquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.cct_titulares
        ///SET
        ///	cct_vigencia    = &apos;BA&apos;,
        ///	cct_fec_baja    = ?,
        ///	cct_ult_act     = ?,
        ///	cct_hora_act    = ?,
        ///	cct_usuario_act = ?,
        ///	cct_campos_act  = ? 
        ///WHERE
        ///	cct_vigencia    = &apos;AC&apos;
        ///	AND
        ///	cct_socio_id    = ?
        ///	AND
        ///	cct_contrat_id  = ?
        ///	AND
        ///	cct_contrato_id = ?.
        /// </summary>
        internal static string spcct_titulares_Actualizar_Baja {
            get {
                return ResourceManager.GetString("spcct_titulares_Actualizar_Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.cct_titulares
        ///SET
        ///	cct_vigencia	 = &apos;AC&apos;,
        ///	cct_fec_reactiva = ?,
        ///	cct_ult_act		 = ?,
        ///	cct_hora_act	 = ?,
        ///	cct_usuario_act  = ?,
        ///	cct_campos_act   = ? 
        ///WHERE
        ///	cct_vigencia    = &apos;BA&apos;
        ///	AND
        ///	cct_socio_id    = ?
        ///	AND
        ///	cct_contrat_id  = ?
        ///	AND
        ///	cct_contrato_id = ?.
        /// </summary>
        internal static string spcct_titulares_Actualizar_Reactivacion {
            get {
                return ResourceManager.GetString("spcct_titulares_Actualizar_Reactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM pub.cct_titulares
        ///WHERE
        ///	cct_vigencia    = &apos;AC&apos;
        ///	AND
        ///	cct_contrat_id  = ?
        ///	AND
        ///	cct_contrato_id = ?
        ///	AND
        ///	cct_socio_id    = ?.
        /// </summary>
        internal static string spcct_titulares_Consultar_PorId {
            get {
                return ResourceManager.GetString("spcct_titulares_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.cct_titulares
        ///(
        ///	cct_campos_act,
        ///	cct_contrat_id,
        ///	cct_contrato_id,
        ///	cct_fec_alta,
        ///	cct_fec_baja,
        ///	cct_hora_act,
        ///	cct_orig_vigen,
        ///	cct_socio_id,
        ///	cct_tipocont,
        ///	cct_ult_act,
        ///	cct_usuario_act,
        ///	cct_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spcct_titulares_Insertar {
            get {
                return ResourceManager.GetString("spcct_titulares_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE PUB.ccu_usuarios SET
        ///	ccu_vigencia	= &apos;BA&apos;,
        ///	ccu_fec_baja	= ?,
        ///	ccu_ult_act		= ?,
        ///	ccu_hora_act    = ?,
        ///	ccu_usuario_act = ?,
        ///	ccu_campos_act  = ? 
        ///WHERE
        ///	ccu_vigencia    = &apos;AC&apos;
        ///	AND
        ///	ccu_socio_id    = ?
        ///	AND
        ///	ccu_cvefam      = ?
        ///	AND
        ///	ccu_contrat_id  = ?
        ///	AND
        ///	ccu_contrato_id = ?.
        /// </summary>
        internal static string spccu_usuarios_Actualizar_Baja {
            get {
                return ResourceManager.GetString("spccu_usuarios_Actualizar_Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE PUB.ccu_usuarios
        ///SET
        ///	ccu_vigencia     = &apos;AC&apos;,
        ///	ccu_fec_reactiva = ?,
        ///	ccu_ult_act      = ?,
        ///	ccu_hora_act     = ?,
        ///	ccu_usuario_act  = ?,
        ///	ccu_campos_act   = ? 
        ///WHERE
        ///	ccu_vigencia    = &apos;BA&apos;
        ///	AND
        ///	ccu_socio_id    = ?
        ///	AND
        ///	ccu_cvefam	    = ?
        ///	AND
        ///	ccu_contrat_id  = ?
        ///	AND
        ///	ccu_contrato_id = ?.
        /// </summary>
        internal static string spccu_usuarios_Actualizar_Reactivacion {
            get {
                return ResourceManager.GetString("spccu_usuarios_Actualizar_Reactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	COUNT(*) GrupoFamiliar
        ///FROM pub.ccu_usuarios cu
        ///WHERE
        ///	cu.ccu_vigencia = &apos;AC&apos;
        ///	AND
        ///	cu.ccu_socio_id = ?.
        /// </summary>
        internal static string spccu_usuarios_Consultar_Count_PorId {
            get {
                return ResourceManager.GetString("spccu_usuarios_Consultar_Count_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM PUB.ccu_usuarios
        ///WHERE
        ///	ccu_vigencia    = &apos;AC&apos;
        ///	AND
        ///	ccu_contrat_id  = ?
        ///	AND
        ///	ccu_contrato_id = ?
        ///	AND
        ///	ccu_socio_id    = ?.
        /// </summary>
        internal static string spccu_usuarios_Consultar_PorId {
            get {
                return ResourceManager.GetString("spccu_usuarios_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string spccu_usuarios_ConsultarPorNumeroSocio {
            get {
                return ResourceManager.GetString("spccu_usuarios_ConsultarPorNumeroSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.ccu_usuarios
        ///(
        ///	ccu_campos_act,
        ///	ccu_contrat_id,
        ///	ccu_contrato_id,
        ///	ccu_cvefam,
        ///	ccu_desc_nomina,
        ///	ccu_fec_alta,
        ///	ccu_fec_baja,
        ///	ccu_hora_act,
        ///	ccu_orig_vigen,
        ///	ccu_socio_id,
        ///	ccu_tipocont,
        ///	ccu_ult_act,
        ///	ccu_usuario_act,
        ///	ccu_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spccu_usuarios_Insertar {
            get {
                return ResourceManager.GetString("spccu_usuarios_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	cl_colonia_id
        ///FROM PUB.cl_colonias
        ///WHERE
        ///	cl_nombre = ?.
        /// </summary>
        internal static string spcl_colonias_Consultar_PorNombre {
            get {
                return ResourceManager.GetString("spcl_colonias_Consultar_PorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM PUB.co_contratos
        ///WHERE
        ///	co_empresa_id = ?
        ///	AND
        ///	co_planta_id  = ?.
        /// </summary>
        internal static string spco_contratos_Consultar_PorId {
            get {
                return ResourceManager.GetString("spco_contratos_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ec_edocivil AS Clave
        ///FROM PUB.ec_edocivil
        ///WHERE ec_edocivil = ?.
        /// </summary>
        internal static string spec_edocivil_Consultar_PorId {
            get {
                return ResourceManager.GetString("spec_edocivil_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ed_edo_id
        ///FROM PUB.ed_estados
        ///WHERE ed_nombre = ?.
        /// </summary>
        internal static string sped_estados_Consultar_PorNombre {
            get {
                return ResourceManager.GetString("sped_estados_Consultar_PorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	mu_muni_id
        ///FROM PUB.mu_municipios
        ///WHERE mu_nombre = ?.
        /// </summary>
        internal static string spmu_municipios_Consultar_PorNombre {
            get {
                return ResourceManager.GetString("spmu_municipios_Consultar_PorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.mvst_movigsercct
        ///(
        ///	mvst_contrat_id,
        ///	mvst_contrato_id,
        ///	mvst_fec_mov,
        ///	mvst_hora_mov,
        ///	mvst_mot_post,
        ///	mvst_motivo_id,
        ///	mvst_orig_vigen,
        ///	mvst_servicio_id,
        ///	mvst_socio_id,
        ///	mvst_usuario,
        ///	mvst_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spmvst_movigsercct_Insertar {
            get {
                return ResourceManager.GetString("spmvst_movigsercct_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.mvsu_movigserccu
        ///(
        ///	mvsu_contrat_id,
        ///	mvsu_contrato_id,
        ///	mvsu_cvefam,
        ///	mvsu_fec_mov,
        ///	mvsu_hora_mov,
        ///	mvsu_mot_post,
        ///	mvsu_motivo_id,
        ///	mvsu_orig_vigen,
        ///	mvsu_servicio_id,
        ///	mvsu_socio_id,
        ///	mvsu_usuario,
        ///	mvsu_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spmvsu_movigserccu_Insertar {
            get {
                return ResourceManager.GetString("spmvsu_movigserccu_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.mvt_movigcct
        ///(
        ///	mvt_contrat_id,
        ///	mvt_contrato_id,
        ///	mvt_fec_mov,
        ///	mvt_hora_mov,
        ///	mvt_mot_post,
        ///	mvt_motivo_id,
        ///	mvt_orig_vigen,
        ///	mvt_socio_id,
        ///	mvt_usuario,
        ///	mvt_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spmvt_movigcct_Insertar {
            get {
                return ResourceManager.GetString("spmvt_movigcct_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.mvu_movigccu
        ///(
        ///	mvu_contrat_id,
        ///	mvu_contrato_id,
        ///	mvu_cvefam,
        ///	mvu_fec_mov,
        ///	mvu_hora_mov,
        ///	mvu_mot_post,
        ///	mvu_motivo_id,
        ///	mvu_orig_vigen,
        ///	mvu_socio_id,
        ///	mvu_usuario,
        ///	mvu_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spmvu_movigccu_Insertar {
            get {
                return ResourceManager.GetString("spmvu_movigccu_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	pa_pais_Id
        ///FROM PUB.pa_pais
        ///WHERE pa_nombre = ? .
        /// </summary>
        internal static string sppa_pais_ConsultarPorNombre {
            get {
                return ResourceManager.GetString("sppa_pais_ConsultarPorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM pub.ps_paqserv
        ///WHERE
        ///	ps_paquete_id = ?.
        /// </summary>
        internal static string spps_paqserv_Consultar_PorId {
            get {
                return ResourceManager.GetString("spps_paqserv_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM PUB.sc_servdecto
        ///WHERE
        ///	sc_vigencia = &apos;AC&apos;
        ///	AND
        ///	sc_contrat_id = ?
        ///	AND
        ///	sc_contrato_id = ?.
        /// </summary>
        internal static string spsc_servdecto_ConsultarPorId {
            get {
                return ResourceManager.GetString("spsc_servdecto_ConsultarPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM pub.sd_serdepaq sd
        ///	JOIN pub.sv_servicios s ON (sd.sd_servicio_id = s.sv_servicio_id)
        ///WHERE
        ///	sd.sd_paquete_id = ?.
        /// </summary>
        internal static string spsd_serdepaq_Consultar_PorId {
            get {
                return ResourceManager.GetString("spsd_serdepaq_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	su.su_servicio_id servicioId,
        ///	co.co_contrat_id,
        ///	co.co_contrato_id 
        ///FROM pub.ccu_usuarios cu 
        ///	JOIN pub.su_serdeusu su  ON (cu.ccu_contrat_id = su.su_contrat_id  AND cu.ccu_contrato_id = su.su_contrato_id AND cu.ccu_socio_id = su.su_socio_id AND cu.ccu_cvefam = su.su_cvefam)
        ///	JOIN pub.co_contratos co ON (cu.ccu_contrat_id = co.co_contrat_id  AND cu.ccu_contrat_id  = co.co_contrat_id)
        ///	JOIN pub.sd_serdepaq sd  ON (sd.sd_paquete_id  = co.co_paquete_id  AND su.su_servicio_id  = sd.sd_servicio_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spsd_serdepaq_Consultar_PorSocioClaveFamId {
            get {
                return ResourceManager.GetString("spsd_serdepaq_Consultar_PorSocioClaveFamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	st.st_servicio_id servicioId,
        ///	co.co_contrat_id,
        ///	co.co_contrato_id 
        ///FROM pub.cct_titulares ct 
        ///	JOIN pub.st_serdetit st  ON (ct.cct_contrat_id = st.st_contrat_id AND ct.cct_contrato_id = st.st_contrato_id AND ct.cct_socio_id = st.st_socio_id)
        ///	JOIN pub.co_contratos co ON (ct.cct_contrat_id = co.co_contrat_id AND ct.cct_contrat_id  = co.co_contrat_id)
        ///	JOIN pub.sd_serdepaq sd  ON (sd.sd_paquete_id  = co.co_paquete_id AND st.st_servicio_id  = sd.sd_servicio_id)
        ///WHERE
        ///	ct.cct_vigencia   = &apos;AC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spsd_serdepaq_Consultar_PorSocioId {
            get {
                return ResourceManager.GetString("spsd_serdepaq_Consultar_PorSocioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.st_serdetit
        ///SET
        ///	st_vigencia    = &apos;BA&apos;,
        ///	st_fec_baja    = ?,
        ///	st_ult_act     = ?,
        ///	st_usuario_act = ?,
        ///	st_hora_act	   = ?,
        ///	st_campos_act  = ? 
        ///WHERE
        ///	st_vigencia    = &apos;AC&apos;
        ///	AND
        ///	st_socio_id    = ?
        ///	AND
        ///	st_contrat_id  = ?
        ///	AND
        ///	st_contrato_id = ?.
        /// </summary>
        internal static string spst_serdetit_Actualizar_Baja {
            get {
                return ResourceManager.GetString("spst_serdetit_Actualizar_Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.st_serdetit
        ///SET
        ///	st_vigencia    = &apos;AC&apos;,
        ///	st_fec_baja    = ?,
        ///	st_ult_act     = ?,
        ///	st_usuario_act = ?,
        ///	st_hora_act	   = ?,
        ///	st_campos_act  = ? 
        ///WHERE
        ///	st_vigencia    = &apos;BA&apos;
        ///	AND
        ///	st_socio_id    = ?
        ///	AND
        ///	st_contrat_id  = ?
        ///	AND
        ///	st_contrato_id = ?.
        /// </summary>
        internal static string spst_serdetit_Actualizar_Reactivacion {
            get {
                return ResourceManager.GetString("spst_serdetit_Actualizar_Reactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM PUB.st_serdetit
        ///WHERE
        ///	st_vigencia    = &apos;AC&apos;
        ///	AND
        ///	st_socio_id    = ?
        ///	AND
        ///	st_contrat_id  = ?
        ///	AND
        ///	st_contrato_id = ?
        ///	AND
        ///	st_servicio_id = ?.
        /// </summary>
        internal static string spst_serdetit_Consultar_PorId {
            get {
                return ResourceManager.GetString("spst_serdetit_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.st_serdetit
        ///(
        ///	st_campos_act,
        ///	st_contrat_id,
        ///	st_contrato_id,
        ///	st_fec_alta,
        ///	st_fec_baja,
        ///	st_hora_act,
        ///	st_orig_vigen,
        ///	st_servicio_id,
        ///	st_socio_id,
        ///	st_ult_act,
        ///	st_usuario_act,
        ///	st_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spst_serdetit_Insertar {
            get {
                return ResourceManager.GetString("spst_serdetit_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.su_serdeusu
        ///SET
        ///	su_vigencia		= &apos;BA&apos;,
        ///	su_fec_reactiva = ?,
        ///	su_ult_act	    = ?,
        ///	su_usuario_act  = ?,
        ///	su_hora_act     = ?,
        ///	su_campos_act   = ? 
        ///WHERE
        ///	su_vigencia    = &apos;AC&apos;
        ///	AND
        ///	su_socio_id    = ?
        ///	AND
        ///	su_cvefam      = ?
        ///	AND
        ///	su_contrat_id  = ?
        ///	AND
        ///	su_contrato_id = ?.
        /// </summary>
        internal static string spsu_serdeusu_Actualizar {
            get {
                return ResourceManager.GetString("spsu_serdeusu_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.su_serdeusu
        ///SET
        ///	su_vigencia    = &apos;BA&apos;,
        ///	su_fec_baja    = ?,
        ///	su_ult_act     = ?,
        ///	su_usuario_act = ?,
        ///	su_hora_act    = ?,
        ///	su_campos_act  = ? 
        ///WHERE
        ///	su_vigencia    = &apos;AC&apos;
        ///	AND
        ///	su_socio_id    = ?
        ///	AND
        ///	su_cvefam	   = ?
        ///	AND
        ///	su_contrat_id  = ?
        ///	AND
        ///	su_contrato_id = ?.
        /// </summary>
        internal static string spsu_serdeusu_Actualizar_Baja {
            get {
                return ResourceManager.GetString("spsu_serdeusu_Actualizar_Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pub.su_serdeusu
        ///SET	su_vigencia     = &apos;AC&apos;,
        ///	su_fec_reactiva = ?,
        ///	su_ult_act		= ?,
        ///	su_usuario_act  = ?,
        ///	su_hora_act		= ?,
        ///	su_campos_act   = ? 
        ///WHERE su_vigencia = &apos;BA&apos;
        ///	AND	su_socio_id    = ?
        ///	AND su_cvefam      = ?
        ///	AND	su_contrat_id  = ?
        ///	AND	su_contrato_id = ?.
        /// </summary>
        internal static string spsu_serdeusu_Actualizar_Reactivacion {
            get {
                return ResourceManager.GetString("spsu_serdeusu_Actualizar_Reactivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM PUB.su_serdeusu
        ///WHERE
        ///	su_vigencia    = &apos;AC&apos;
        ///	AND
        ///	su_socio_id    = ?
        ///	AND
        ///	su_contrat_id  = ?
        ///	AND
        ///	su_contrato_id = ?
        ///	AND
        ///	su_servicio_id = ?.
        /// </summary>
        internal static string spsu_serdeusu_Consultar_PorId {
            get {
                return ResourceManager.GetString("spsu_serdeusu_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.su_serdeusu
        ///(
        ///	su_campos_act,
        ///	su_contrat_id,
        ///	su_contrato_id,
        ///	su_cvefam,
        ///	su_fec_alta,
        ///	su_fec_baja,
        ///	su_hora_act,
        ///	su_orig_vigen,
        ///	su_servicio_id,
        ///	su_socio_id,
        ///	su_ult_act,
        ///	su_usuario_act,
        ///	su_vigencia
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?
        ///).
        /// </summary>
        internal static string spsu_serdeusu_Insertar {
            get {
                return ResourceManager.GetString("spsu_serdeusu_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE	pub.ti_titulares
        ///SET		ti_gpofam = ?
        ///WHERE	ti_socio_id = ?.
        /// </summary>
        internal static string spti_titulares_Actualizar_GopFam_PorId {
            get {
                return ResourceManager.GetString("spti_titulares_Actualizar_GopFam_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE	pub.ti_titulares
        ///SET		ti_nombrecompleto = ?,
        ///		ti_calle		  = ?,
        ///		ti_numdir		  = ?,
        ///		ti_colonia_id	  = ?,
        ///		ti_codigopost	  = ?,
        ///		ti_telefono_casa  = ?,
        ///		ti_telefono_ofi   = ?,
        ///		ti_extension	  = ?, 
        ///		ti_fax			  = ?,
        ///		ti_correoelec	  = ?,
        ///		ti_gpofam		  = ?,
        ///		ti_edocivil	      = ?,
        ///		ti_campos_act	  = ?,
        ///		ti_rfc			  = ?,
        ///		ti_empresa_id     = ?,
        ///		ti_planta_id      = ?,
        ///		ti_depto_id       = ?,
        ///		ti_fecing_emp     = ?,
        ///		ti_muni_id        = ?,
        ///		ti_segusoc	      = ?,
        ///		ti_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spti_titulares_Actualizar_Todo_PorId {
            get {
                return ResourceManager.GetString("spti_titulares_Actualizar_Todo_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	ti_socio_id AS Clave
        ///FROM	pub.ti_titulares
        ///WHERE	ti_socio_id = ?.
        /// </summary>
        internal static string spti_titulares_Consultar_PorId {
            get {
                return ResourceManager.GetString("spti_titulares_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.ti_titulares
        ///(
        ///	ti_calle,
        ///	ti_campos_act,
        ///	ti_codigopost,
        ///	ti_colonia_id,
        ///	ti_correoelec,
        ///	ti_depto_id,
        ///	ti_edocivil,
        ///	ti_empresa_id,
        ///	ti_extension,
        ///	ti_fax,
        ///	ti_fec_alta,
        ///	ti_fecing_emp,
        ///	ti_fecing_gpo,
        ///	ti_gpofam,
        ///	ti_hora_act,
        ///	ti_muni_id,
        ///	ti_nombrecompleto,
        ///	ti_numdir,
        ///	ti_planta_id,
        ///	ti_rfc,
        ///	ti_segusoc,
        ///	ti_socio_id,
        ///	ti_telefono_casa,
        ///	ti_telefono_ofi,
        ///	ti_tipotrab,
        ///	ti_ult_act,
        ///	ti_usuario_act
        ///)
        ///VALUES
        ///(
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	?,
        ///	? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spti_titulares_Insertar {
            get {
                return ResourceManager.GetString("spti_titulares_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(tmu_folio) as FolioMaximo FROM PUB.tmu_usuarios.
        /// </summary>
        internal static string sptmu_usuarios_Consultar_Maximo_Folio {
            get {
                return ResourceManager.GetString("sptmu_usuarios_Consultar_Maximo_Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	tmu_aplica_fam, 
        ///	tmu_ap_casada, 
        ///	tmu_ap_mat, 
        ///	tmu_ap_pat, 
        ///	tmu_calle, 
        ///	tmu_codigopost, 
        ///	tmu_colonia_desc, 
        ///	tmu_colonia_id, 
        ///	tmu_correoelec, 
        ///	tmu_curp, 
        ///	tmu_cvefam, 
        ///	tmu_cvefam_ant, 
        ///	tmu_cve_estatus, 
        ///	tmu_cve_mov, 
        ///	tmu_depto_id, 
        ///	tmu_desc_nomina, 
        ///	tmu_edocivil, 
        ///	tmu_empresa_id, 
        ///	tmu_Endoso_SIASS, 
        ///	tmu_estado_desc, 
        ///	tmu_estado_id, 
        ///	tmu_extension, 
        ///	tmu_fax_movil, 
        ///	tmu_fec_alta, 
        ///	tmu_fec_baja, 
        ///	tmu_fec_captura, 
        ///	tmu_fec_fallecimiento, 
        ///	tmu_fec_naci, 
        ///	tmu_fec_proceso, 
        ///	tmu_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sptmu_usuarios_ConsultarPorCurp {
            get {
                return ResourceManager.GetString("sptmu_usuarios_ConsultarPorCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.tmu_usuarios
        ///(
        ///	tmu_aplica_fam, 
        ///	tmu_ap_casada, 
        ///	tmu_ap_mat, 
        ///	tmu_ap_pat, 
        ///	tmu_calle, 
        ///	tmu_codigopost, 
        ///	tmu_colonia_desc, 
        ///	tmu_colonia_id, 
        ///	tmu_correoelec, 
        ///	tmu_curp, 
        ///	tmu_cvefam, 
        ///	tmu_cvefam_ant, 
        ///	tmu_cve_estatus, 
        ///	tmu_cve_mov, 
        ///	tmu_depto_id, 
        ///	tmu_desc_nomina, 
        ///	tmu_edocivil, 
        ///	tmu_empresa_id, 
        ///	tmu_Endoso_SIASS, 
        ///	tmu_estado_desc, 
        ///	tmu_estado_id, 
        ///	tmu_extension, 
        ///	tmu_fax_movil, 
        ///	tmu_fec_alta, 
        ///	tmu_fec_baja, 
        ///	tmu_fec_captura, 
        ///	tmu_fec_fallecimiento, 
        ///	tmu_fec_naci, 
        ///	t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sptmu_usuarios_Insertar {
            get {
                return ResourceManager.GetString("sptmu_usuarios_Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	tu_tipous_id AS Clave
        ///FROM PUB.tu_tipousuario
        ///WHERE tu_tipous_id = ?.
        /// </summary>
        internal static string sptu_tipoUsuario_Consultar_PorTipoId {
            get {
                return ResourceManager.GetString("sptu_tipoUsuario_Consultar_PorTipoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE PUB.us_usuarios
        ///SET Id_Enlace			   = ?,
        ///	Id_SIASS			   = ?,
        ///	us_apellidomat		   = ?,
        ///	us_apellidopat		   = ?,
        ///	us_Beca				   = ?,
        ///	us_cadena_confirmacion = ?,
        ///	us_calle			   = ?,
        ///	us_campos_act		   = ?, 
        ///	us_codigopost		   = ?,
        ///	us_colonia_desc		   = ?,
        ///	us_colonia_id		   = ?,
        ///	us_correo_confirmado   = ?,
        ///	us_correoelec		   = ?,
        ///	us_curp				   = ?,
        ///	us_curp_provisional    = ?,
        ///	us_edocivil			   = ?,
        ///	us_estudiante		   = ?,
        ///	us_extension		   = ?,
        ///	us_fax_movil		   = ?,
        ///	us_fec_naci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spus_usuarios_Actualizar_Todo_PorId {
            get {
                return ResourceManager.GetString("spus_usuarios_Actualizar_Todo_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id_Enlace, 
        ///	Id_SIASS, 
        ///	us_apellidomat, 
        ///	us_apellidopat, 
        ///	us_Beca, 
        ///	us_cadena_confirmacion, 
        ///	us_calle, 
        ///	us_campos_act, 
        ///	us_codigopost, 
        ///	us_colonia_desc, 
        ///	us_colonia_id, 
        ///	us_correo_confirmado, 
        ///	us_correoelec, 
        ///	us_curp, 
        ///	us_curp_provisional, 
        ///	us_cvefam, 
        ///	us_edocivil, 
        ///	us_estudiante, 
        ///	us_extension, 
        ///	us_fax_movil, 
        ///	us_fec_alta, 
        ///	us_fec_naci, 
        ///	us_hora_act, 
        ///	us_muni_id, 
        ///	us_nombre, 
        ///	us_num_ternium, 
        ///	us_numdir, 
        ///	us_pais_id, 
        ///	us_pass_www, 
        ///	us_pregunta, 
        ///	us_respuesta, 
        ///	us_rfc,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spus_usuarios_ConsultaPorCURP {
            get {
                return ResourceManager.GetString("spus_usuarios_ConsultaPorCURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id_Enlace, 
        ///	Id_SIASS, 
        ///	us_apellidomat, 
        ///	us_apellidopat, 
        ///	us_Beca, 
        ///	us_cadena_confirmacion, 
        ///	us_calle, 
        ///	us_campos_act, 
        ///	us_codigopost, 
        ///	us_colonia_desc, 
        ///	us_colonia_id, 
        ///	us_correo_confirmado, 
        ///	us_correoelec, 
        ///	us_curp, 
        ///	us_curp_provisional, 
        ///	us_cvefam, 
        ///	us_edocivil, 
        ///	us_estudiante, 
        ///	us_extension, 
        ///	us_fax_movil, 
        ///	us_fec_alta, 
        ///	us_fec_naci, 
        ///	us_hora_act, 
        ///	us_muni_id, 
        ///	us_nombre, 
        ///	us_num_ternium, 
        ///	us_numdir, 
        ///	us_pais_id, 
        ///	us_pass_www, 
        ///	us_pregunta, 
        ///	us_respuesta, 
        ///	us_rfc,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spus_usuarios_ConsultaPorId {
            get {
                return ResourceManager.GetString("spus_usuarios_ConsultaPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	us_socio_id,
        ///	us_cvefam
        ///FROM pub.us_usuarios
        ///WHERE us_socio_id = ?.
        /// </summary>
        internal static string spus_usuarios_Consultar_PorId {
            get {
                return ResourceManager.GetString("spus_usuarios_Consultar_PorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_SIASS
        ///FROM pub.us_usuarios
        ///WHERE Id_SIASS = ?
        ///AND (us_socio_id &lt;&gt; ?
        ///OR us_cvefam &lt;&gt; ?).
        /// </summary>
        internal static string spus_usuarios_Consultar_PorSIASS {
            get {
                return ResourceManager.GetString("spus_usuarios_Consultar_PorSIASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	us_socio_id,
        ///	us_cvefam
        ///FROM pub.us_usuarios
        ///WHERE
        ///	us_socio_id = ?
        ///	AND
        ///	us_cvefam   = ?.
        /// </summary>
        internal static string spus_usuarios_Consultar_PorSocioClaveFamId {
            get {
                return ResourceManager.GetString("spus_usuarios_Consultar_PorSocioClaveFamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PUB.us_usuarios
        ///(
        ///	Id_Enlace,
        ///	Id_SIASS,
        ///	us_apellidomat,
        ///	us_apellidopat,
        ///	us_Beca,
        ///	us_cadena_confirmacion,
        ///	us_calle,
        ///	us_campos_act,
        ///	us_codigopost,
        ///	us_colonia_desc,
        ///	us_colonia_id,
        ///	us_correo_confirmado,
        ///	us_correoelec,
        ///	us_curp,
        ///	us_curp_provisional,
        ///	us_cvefam,
        ///	us_edocivil,
        ///	us_estudiante,
        ///	us_extension,
        ///	us_fax_movil,
        ///	us_fec_alta,
        ///	us_fec_naci,
        ///	us_hora_act,
        ///	us_muni_id,
        ///	us_nombre,
        ///	us_num_ternium,
        ///	us_numdir,
        ///	us_pais_id,
        ///	us_pass_www,
        ///	us_pregunta,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spus_usuarios_Insertar {
            get {
                return ResourceManager.GetString("spus_usuarios_Insertar", resourceCulture);
            }
        }
    }
}
