//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SACC.Test.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosAlta", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class DatosAlta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoCasadaEsposaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEmpresaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePlantaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveTipoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAltaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaBajaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAfiliacionIMSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEndosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoCasadaEsposa {
            get {
                return this.ApellidoCasadaEsposaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoCasadaEsposaField, value) != true)) {
                    this.ApellidoCasadaEsposaField = value;
                    this.RaisePropertyChanged("ApellidoCasadaEsposa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEmpresaContrato {
            get {
                return this.ClaveEmpresaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEmpresaContratoField, value) != true)) {
                    this.ClaveEmpresaContratoField = value;
                    this.RaisePropertyChanged("ClaveEmpresaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEstadoCivil {
            get {
                return this.ClaveEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEstadoCivilField, value) != true)) {
                    this.ClaveEstadoCivilField = value;
                    this.RaisePropertyChanged("ClaveEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveFamiliar {
            get {
                return this.ClaveFamiliarField;
            }
            set {
                if ((this.ClaveFamiliarField.Equals(value) != true)) {
                    this.ClaveFamiliarField = value;
                    this.RaisePropertyChanged("ClaveFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePlantaContrato {
            get {
                return this.ClavePlantaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePlantaContratoField, value) != true)) {
                    this.ClavePlantaContratoField = value;
                    this.RaisePropertyChanged("ClavePlantaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveTipoSanguineo {
            get {
                return this.ClaveTipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveTipoSanguineoField, value) != true)) {
                    this.ClaveTipoSanguineoField = value;
                    this.RaisePropertyChanged("ClaveTipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((this.ExtensionField.Equals(value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((this.FaxField.Equals(value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAltaContrato {
            get {
                return this.FechaAltaContratoField;
            }
            set {
                if ((this.FechaAltaContratoField.Equals(value) != true)) {
                    this.FechaAltaContratoField = value;
                    this.RaisePropertyChanged("FechaAltaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaBajaContrato {
            get {
                return this.FechaBajaContratoField;
            }
            set {
                if ((this.FechaBajaContratoField.Equals(value) != true)) {
                    this.FechaBajaContratoField = value;
                    this.RaisePropertyChanged("FechaBajaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMovimiento {
            get {
                return this.FechaMovimientoField;
            }
            set {
                if ((this.FechaMovimientoField.Equals(value) != true)) {
                    this.FechaMovimientoField = value;
                    this.RaisePropertyChanged("FechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAfiliacionIMSS {
            get {
                return this.NumeroAfiliacionIMSSField;
            }
            set {
                if ((this.NumeroAfiliacionIMSSField.Equals(value) != true)) {
                    this.NumeroAfiliacionIMSSField = value;
                    this.RaisePropertyChanged("NumeroAfiliacionIMSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEndoso {
            get {
                return this.NumeroEndosoField;
            }
            set {
                if ((this.NumeroEndosoField.Equals(value) != true)) {
                    this.NumeroEndosoField = value;
                    this.RaisePropertyChanged("NumeroEndoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((this.NumeroPolizaField.Equals(value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSocio {
            get {
                return this.NumeroSocioField;
            }
            set {
                if ((this.NumeroSocioField.Equals(value) != true)) {
                    this.NumeroSocioField = value;
                    this.RaisePropertyChanged("NumeroSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCSocio {
            get {
                return this.RFCSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCSocioField, value) != true)) {
                    this.RFCSocioField = value;
                    this.RaisePropertyChanged("RFCSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocioId {
            get {
                return this.SocioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioIdField, value) != true)) {
                    this.SocioIdField = value;
                    this.RaisePropertyChanged("SocioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((this.TelefonoCasaField.Equals(value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoOficina {
            get {
                return this.TelefonoOficinaField;
            }
            set {
                if ((this.TelefonoOficinaField.Equals(value) != true)) {
                    this.TelefonoOficinaField = value;
                    this.RaisePropertyChanged("TelefonoOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTrabajador {
            get {
                return this.TipoTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTrabajadorField, value) != true)) {
                    this.TipoTrabajadorField = value;
                    this.RaisePropertyChanged("TipoTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TransaccionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransaccionId {
            get {
                return this.TransaccionIdField;
            }
            set {
                if ((this.TransaccionIdField.Equals(value) != true)) {
                    this.TransaccionIdField = value;
                    this.RaisePropertyChanged("TransaccionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosCambio", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class DatosCambio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoCasadaEsposaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEmpresaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClavePaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePlantaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveTipoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAfiliacionIMSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEndosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoCasadaEsposa {
            get {
                return this.ApellidoCasadaEsposaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoCasadaEsposaField, value) != true)) {
                    this.ApellidoCasadaEsposaField = value;
                    this.RaisePropertyChanged("ApellidoCasadaEsposa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveCiudad {
            get {
                return this.ClaveCiudadField;
            }
            set {
                if ((this.ClaveCiudadField.Equals(value) != true)) {
                    this.ClaveCiudadField = value;
                    this.RaisePropertyChanged("ClaveCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveColonia {
            get {
                return this.ClaveColoniaField;
            }
            set {
                if ((this.ClaveColoniaField.Equals(value) != true)) {
                    this.ClaveColoniaField = value;
                    this.RaisePropertyChanged("ClaveColonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEmpresaContrato {
            get {
                return this.ClaveEmpresaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEmpresaContratoField, value) != true)) {
                    this.ClaveEmpresaContratoField = value;
                    this.RaisePropertyChanged("ClaveEmpresaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveEstado {
            get {
                return this.ClaveEstadoField;
            }
            set {
                if ((this.ClaveEstadoField.Equals(value) != true)) {
                    this.ClaveEstadoField = value;
                    this.RaisePropertyChanged("ClaveEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEstadoCivil {
            get {
                return this.ClaveEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEstadoCivilField, value) != true)) {
                    this.ClaveEstadoCivilField = value;
                    this.RaisePropertyChanged("ClaveEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveFamiliar {
            get {
                return this.ClaveFamiliarField;
            }
            set {
                if ((this.ClaveFamiliarField.Equals(value) != true)) {
                    this.ClaveFamiliarField = value;
                    this.RaisePropertyChanged("ClaveFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClavePais {
            get {
                return this.ClavePaisField;
            }
            set {
                if ((this.ClavePaisField.Equals(value) != true)) {
                    this.ClavePaisField = value;
                    this.RaisePropertyChanged("ClavePais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePlantaContrato {
            get {
                return this.ClavePlantaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePlantaContratoField, value) != true)) {
                    this.ClavePlantaContratoField = value;
                    this.RaisePropertyChanged("ClavePlantaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveTipoSanguineo {
            get {
                return this.ClaveTipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveTipoSanguineoField, value) != true)) {
                    this.ClaveTipoSanguineoField = value;
                    this.RaisePropertyChanged("ClaveTipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((this.ExtensionField.Equals(value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((this.FaxField.Equals(value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMovimiento {
            get {
                return this.FechaMovimientoField;
            }
            set {
                if ((this.FechaMovimientoField.Equals(value) != true)) {
                    this.FechaMovimientoField = value;
                    this.RaisePropertyChanged("FechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAfiliacionIMSS {
            get {
                return this.NumeroAfiliacionIMSSField;
            }
            set {
                if ((this.NumeroAfiliacionIMSSField.Equals(value) != true)) {
                    this.NumeroAfiliacionIMSSField = value;
                    this.RaisePropertyChanged("NumeroAfiliacionIMSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEndoso {
            get {
                return this.NumeroEndosoField;
            }
            set {
                if ((this.NumeroEndosoField.Equals(value) != true)) {
                    this.NumeroEndosoField = value;
                    this.RaisePropertyChanged("NumeroEndoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((this.NumeroPolizaField.Equals(value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSocio {
            get {
                return this.NumeroSocioField;
            }
            set {
                if ((this.NumeroSocioField.Equals(value) != true)) {
                    this.NumeroSocioField = value;
                    this.RaisePropertyChanged("NumeroSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCSocio {
            get {
                return this.RFCSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCSocioField, value) != true)) {
                    this.RFCSocioField = value;
                    this.RaisePropertyChanged("RFCSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocioId {
            get {
                return this.SocioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioIdField, value) != true)) {
                    this.SocioIdField = value;
                    this.RaisePropertyChanged("SocioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((this.TelefonoCasaField.Equals(value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoOficina {
            get {
                return this.TelefonoOficinaField;
            }
            set {
                if ((this.TelefonoOficinaField.Equals(value) != true)) {
                    this.TelefonoOficinaField = value;
                    this.RaisePropertyChanged("TelefonoOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTrabajador {
            get {
                return this.TipoTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTrabajadorField, value) != true)) {
                    this.TipoTrabajadorField = value;
                    this.RaisePropertyChanged("TipoTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosBaja", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class DatosBaja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoCasadaEsposaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEmpresaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePlantaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveTipoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaBajaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAfiliacionIMSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEndosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoCasadaEsposa {
            get {
                return this.ApellidoCasadaEsposaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoCasadaEsposaField, value) != true)) {
                    this.ApellidoCasadaEsposaField = value;
                    this.RaisePropertyChanged("ApellidoCasadaEsposa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEmpresaContrato {
            get {
                return this.ClaveEmpresaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEmpresaContratoField, value) != true)) {
                    this.ClaveEmpresaContratoField = value;
                    this.RaisePropertyChanged("ClaveEmpresaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEstadoCivil {
            get {
                return this.ClaveEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEstadoCivilField, value) != true)) {
                    this.ClaveEstadoCivilField = value;
                    this.RaisePropertyChanged("ClaveEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveFamiliar {
            get {
                return this.ClaveFamiliarField;
            }
            set {
                if ((this.ClaveFamiliarField.Equals(value) != true)) {
                    this.ClaveFamiliarField = value;
                    this.RaisePropertyChanged("ClaveFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePlantaContrato {
            get {
                return this.ClavePlantaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePlantaContratoField, value) != true)) {
                    this.ClavePlantaContratoField = value;
                    this.RaisePropertyChanged("ClavePlantaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveTipoSanguineo {
            get {
                return this.ClaveTipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveTipoSanguineoField, value) != true)) {
                    this.ClaveTipoSanguineoField = value;
                    this.RaisePropertyChanged("ClaveTipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((this.ExtensionField.Equals(value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((this.FaxField.Equals(value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaBajaContrato {
            get {
                return this.FechaBajaContratoField;
            }
            set {
                if ((this.FechaBajaContratoField.Equals(value) != true)) {
                    this.FechaBajaContratoField = value;
                    this.RaisePropertyChanged("FechaBajaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMovimiento {
            get {
                return this.FechaMovimientoField;
            }
            set {
                if ((this.FechaMovimientoField.Equals(value) != true)) {
                    this.FechaMovimientoField = value;
                    this.RaisePropertyChanged("FechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAfiliacionIMSS {
            get {
                return this.NumeroAfiliacionIMSSField;
            }
            set {
                if ((this.NumeroAfiliacionIMSSField.Equals(value) != true)) {
                    this.NumeroAfiliacionIMSSField = value;
                    this.RaisePropertyChanged("NumeroAfiliacionIMSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEndoso {
            get {
                return this.NumeroEndosoField;
            }
            set {
                if ((this.NumeroEndosoField.Equals(value) != true)) {
                    this.NumeroEndosoField = value;
                    this.RaisePropertyChanged("NumeroEndoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((this.NumeroPolizaField.Equals(value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSocio {
            get {
                return this.NumeroSocioField;
            }
            set {
                if ((this.NumeroSocioField.Equals(value) != true)) {
                    this.NumeroSocioField = value;
                    this.RaisePropertyChanged("NumeroSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCSocio {
            get {
                return this.RFCSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCSocioField, value) != true)) {
                    this.RFCSocioField = value;
                    this.RaisePropertyChanged("RFCSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocioId {
            get {
                return this.SocioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioIdField, value) != true)) {
                    this.SocioIdField = value;
                    this.RaisePropertyChanged("SocioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((this.TelefonoCasaField.Equals(value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoOficina {
            get {
                return this.TelefonoOficinaField;
            }
            set {
                if ((this.TelefonoOficinaField.Equals(value) != true)) {
                    this.TelefonoOficinaField = value;
                    this.RaisePropertyChanged("TelefonoOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTrabajador {
            get {
                return this.TipoTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTrabajadorField, value) != true)) {
                    this.TipoTrabajadorField = value;
                    this.RaisePropertyChanged("TipoTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosReactivacion", Namespace="http://schemas.datacontract.org/2004/07/wsSACC")]
    [System.SerializableAttribute()]
    public partial class DatosReactivacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoCasadaEsposaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEmpresaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaveFamiliarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClavePaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClavePlantaContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveTipoSanguineoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReactivacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroAfiliacionIMSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEndosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPolizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoCasadaEsposa {
            get {
                return this.ApellidoCasadaEsposaField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoCasadaEsposaField, value) != true)) {
                    this.ApellidoCasadaEsposaField = value;
                    this.RaisePropertyChanged("ApellidoCasadaEsposa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveCiudad {
            get {
                return this.ClaveCiudadField;
            }
            set {
                if ((this.ClaveCiudadField.Equals(value) != true)) {
                    this.ClaveCiudadField = value;
                    this.RaisePropertyChanged("ClaveCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveColonia {
            get {
                return this.ClaveColoniaField;
            }
            set {
                if ((this.ClaveColoniaField.Equals(value) != true)) {
                    this.ClaveColoniaField = value;
                    this.RaisePropertyChanged("ClaveColonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEmpresaContrato {
            get {
                return this.ClaveEmpresaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEmpresaContratoField, value) != true)) {
                    this.ClaveEmpresaContratoField = value;
                    this.RaisePropertyChanged("ClaveEmpresaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveEstado {
            get {
                return this.ClaveEstadoField;
            }
            set {
                if ((this.ClaveEstadoField.Equals(value) != true)) {
                    this.ClaveEstadoField = value;
                    this.RaisePropertyChanged("ClaveEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEstadoCivil {
            get {
                return this.ClaveEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEstadoCivilField, value) != true)) {
                    this.ClaveEstadoCivilField = value;
                    this.RaisePropertyChanged("ClaveEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaveFamiliar {
            get {
                return this.ClaveFamiliarField;
            }
            set {
                if ((this.ClaveFamiliarField.Equals(value) != true)) {
                    this.ClaveFamiliarField = value;
                    this.RaisePropertyChanged("ClaveFamiliar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClavePais {
            get {
                return this.ClavePaisField;
            }
            set {
                if ((this.ClavePaisField.Equals(value) != true)) {
                    this.ClavePaisField = value;
                    this.RaisePropertyChanged("ClavePais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClavePlantaContrato {
            get {
                return this.ClavePlantaContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClavePlantaContratoField, value) != true)) {
                    this.ClavePlantaContratoField = value;
                    this.RaisePropertyChanged("ClavePlantaContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveTipoSanguineo {
            get {
                return this.ClaveTipoSanguineoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveTipoSanguineoField, value) != true)) {
                    this.ClaveTipoSanguineoField = value;
                    this.RaisePropertyChanged("ClaveTipoSanguineo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colonia {
            get {
                return this.ColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColoniaField, value) != true)) {
                    this.ColoniaField = value;
                    this.RaisePropertyChanged("Colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((this.ExtensionField.Equals(value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((this.FaxField.Equals(value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMovimiento {
            get {
                return this.FechaMovimientoField;
            }
            set {
                if ((this.FechaMovimientoField.Equals(value) != true)) {
                    this.FechaMovimientoField = value;
                    this.RaisePropertyChanged("FechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReactivacion {
            get {
                return this.FechaReactivacionField;
            }
            set {
                if ((this.FechaReactivacionField.Equals(value) != true)) {
                    this.FechaReactivacionField = value;
                    this.RaisePropertyChanged("FechaReactivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroAfiliacionIMSS {
            get {
                return this.NumeroAfiliacionIMSSField;
            }
            set {
                if ((this.NumeroAfiliacionIMSSField.Equals(value) != true)) {
                    this.NumeroAfiliacionIMSSField = value;
                    this.RaisePropertyChanged("NumeroAfiliacionIMSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEndoso {
            get {
                return this.NumeroEndosoField;
            }
            set {
                if ((this.NumeroEndosoField.Equals(value) != true)) {
                    this.NumeroEndosoField = value;
                    this.RaisePropertyChanged("NumeroEndoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroExterior {
            get {
                return this.NumeroExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroExteriorField, value) != true)) {
                    this.NumeroExteriorField = value;
                    this.RaisePropertyChanged("NumeroExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPoliza {
            get {
                return this.NumeroPolizaField;
            }
            set {
                if ((this.NumeroPolizaField.Equals(value) != true)) {
                    this.NumeroPolizaField = value;
                    this.RaisePropertyChanged("NumeroPoliza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroSocio {
            get {
                return this.NumeroSocioField;
            }
            set {
                if ((this.NumeroSocioField.Equals(value) != true)) {
                    this.NumeroSocioField = value;
                    this.RaisePropertyChanged("NumeroSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCSocio {
            get {
                return this.RFCSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCSocioField, value) != true)) {
                    this.RFCSocioField = value;
                    this.RaisePropertyChanged("RFCSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocioId {
            get {
                return this.SocioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioIdField, value) != true)) {
                    this.SocioIdField = value;
                    this.RaisePropertyChanged("SocioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((this.TelefonoCasaField.Equals(value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TelefonoOficina {
            get {
                return this.TelefonoOficinaField;
            }
            set {
                if ((this.TelefonoOficinaField.Equals(value) != true)) {
                    this.TelefonoOficinaField = value;
                    this.RaisePropertyChanged("TelefonoOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTrabajador {
            get {
                return this.TipoTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTrabajadorField, value) != true)) {
                    this.TipoTrabajadorField = value;
                    this.RaisePropertyChanged("TipoTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVigencia")]
    public interface IVigencia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/AltaAsociado", ReplyAction="http://tempuri.org/IVigencia/AltaAsociadoResponse")]
        SACC.Test.ServiceReference1.Respuesta AltaAsociado(SACC.Test.ServiceReference1.DatosAlta asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/AltaAsociado", ReplyAction="http://tempuri.org/IVigencia/AltaAsociadoResponse")]
        System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> AltaAsociadoAsync(SACC.Test.ServiceReference1.DatosAlta asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/CambioAsociado", ReplyAction="http://tempuri.org/IVigencia/CambioAsociadoResponse")]
        SACC.Test.ServiceReference1.Respuesta CambioAsociado(SACC.Test.ServiceReference1.DatosCambio asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/CambioAsociado", ReplyAction="http://tempuri.org/IVigencia/CambioAsociadoResponse")]
        System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> CambioAsociadoAsync(SACC.Test.ServiceReference1.DatosCambio asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/BajaAsociado", ReplyAction="http://tempuri.org/IVigencia/BajaAsociadoResponse")]
        SACC.Test.ServiceReference1.Respuesta BajaAsociado(SACC.Test.ServiceReference1.DatosBaja asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/BajaAsociado", ReplyAction="http://tempuri.org/IVigencia/BajaAsociadoResponse")]
        System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> BajaAsociadoAsync(SACC.Test.ServiceReference1.DatosBaja asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/ReactivaAsociado", ReplyAction="http://tempuri.org/IVigencia/ReactivaAsociadoResponse")]
        SACC.Test.ServiceReference1.Respuesta ReactivaAsociado(SACC.Test.ServiceReference1.DatosReactivacion asociado, SACC.Test.ServiceReference1.Token pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVigencia/ReactivaAsociado", ReplyAction="http://tempuri.org/IVigencia/ReactivaAsociadoResponse")]
        System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> ReactivaAsociadoAsync(SACC.Test.ServiceReference1.DatosReactivacion asociado, SACC.Test.ServiceReference1.Token pToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVigenciaChannel : SACC.Test.ServiceReference1.IVigencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VigenciaClient : System.ServiceModel.ClientBase<SACC.Test.ServiceReference1.IVigencia>, SACC.Test.ServiceReference1.IVigencia {
        
        public VigenciaClient() {
        }
        
        public VigenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VigenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VigenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VigenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SACC.Test.ServiceReference1.Respuesta AltaAsociado(SACC.Test.ServiceReference1.DatosAlta asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.AltaAsociado(asociado, pToken);
        }
        
        public System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> AltaAsociadoAsync(SACC.Test.ServiceReference1.DatosAlta asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.AltaAsociadoAsync(asociado, pToken);
        }
        
        public SACC.Test.ServiceReference1.Respuesta CambioAsociado(SACC.Test.ServiceReference1.DatosCambio asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.CambioAsociado(asociado, pToken);
        }
        
        public System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> CambioAsociadoAsync(SACC.Test.ServiceReference1.DatosCambio asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.CambioAsociadoAsync(asociado, pToken);
        }
        
        public SACC.Test.ServiceReference1.Respuesta BajaAsociado(SACC.Test.ServiceReference1.DatosBaja asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.BajaAsociado(asociado, pToken);
        }
        
        public System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> BajaAsociadoAsync(SACC.Test.ServiceReference1.DatosBaja asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.BajaAsociadoAsync(asociado, pToken);
        }
        
        public SACC.Test.ServiceReference1.Respuesta ReactivaAsociado(SACC.Test.ServiceReference1.DatosReactivacion asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.ReactivaAsociado(asociado, pToken);
        }
        
        public System.Threading.Tasks.Task<SACC.Test.ServiceReference1.Respuesta> ReactivaAsociadoAsync(SACC.Test.ServiceReference1.DatosReactivacion asociado, SACC.Test.ServiceReference1.Token pToken) {
            return base.Channel.ReactivaAsociadoAsync(asociado, pToken);
        }
    }
}
